name: Deploy on push

on:
  push:
    branches:
      - main
  schedule:
    # Run at 4:25 UTC at every 10th day of the month
    # Point is to do it monthly; the exact time is picked semi-randomly to
    # spread out GitHub and Invent's load
    - cron: "25 4 10 * *"

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install -p
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: make deploy
